import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/navbar/navbar'
import { TProvider } from './components/theme/themeprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col items-center justify-between bg-base-100 px-16 py-8">
          <TProvider>
            <NavBar />
            {children}
          </TProvider>
        </div>
      </body>
    </html>
  )
}
